### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by etzl** [etzl/among-stars#13]

**Comment by abel-mak** [comment]
Hello @etzl, i want to work on this.

**Comment by etzl** [comment]
Hi @abel-mak. Cool, let me know if you need any additional details.

There are a lot of warnings about implicit cast, from my understanding you need to use `static_cast`, but might be different in each situation

**Comment by mfurkaner** [comment]
Is the project buildable atm? I can't build in macOS. 
<img width="1089" alt="Screen Shot 2022-03-30 at 23 21 06" src="https://user-images.githubusercontent.com/48824447/160924107-dcb7f8c5-a37f-487f-8d8a-83f6f870c621.png">

**Comment by etzl** [comment]
@mfurkaner Your system is using `clang` by default which gives this error on my system too. You need to change that to GCC compiler to use `g++` command. The make file *is* using g++ so I'm guessing you don't have it installed.

This definitely needs to be fixed in the future (and the compiler suggests a fix) but if you want to compile it now, this is probably the only way. I haven't built the project on mac so if there was any other problem, please open an issue :v:

**Comment by mfurkaner** [comment]
I do have gcc and use it on my projects though. Strange

**Comment by etzl** [comment]
@mfurkaner That's interesting. Can you open an issue? If yes, include any information that you think might be helpful, like the compiler version, ...

**Comment by etzl** [comment]
fixed #19
