### ISSUE TITLE
player collision

### ISSUE THREAD

**Issue by abel-mak** [etzl/among-stars#20]
player gets outside the window when moving horizontally

**Comment by etzl** [comment]
A quick solution can be `maxx` to get the maximum possible value of the current window and check the player's `x` to be within range `0` and `maxx`.

But a more elegant solution is designing a base class (#4) to apply this to all objects. I'm still not sure how to implement such a base class, as I've had tried before without success

**Comment by etzl** [comment]
fixed https://github.com/etzl/among-stars/commit/bf100e69e485b824ebe41cae5ed18094cf39c20b
